apiVersion: v1
kind: Service
metadata:
 name: platformnpservice-srv
spec:
 type: NodePort
 selector:  
  app: plaformservice
 ports:
  - name: plaformservice
    protocol: TCP
    port: 80
    targetPort: 80

 